#!/usr/bin/env python3
"""Generate deterministic shell completions and the exhaustive command reference."""

import argparse
import re
import subprocess
from pathlib import Path


SUBCOMMAND = re.compile(r"^    ([a-z][a-z0-9-]*)\s{2,}")


def run(binary, *args):
    result = subprocess.run(
        [str(binary), *args], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    if result.stderr:
        raise SystemExit(result.stderr.decode(errors="replace"))
    return result.stdout


def child_names(help_text):
    in_subcommands = False
    names = []
    for line in help_text.splitlines():
        if line == "SUBCOMMANDS:":
            in_subcommands = True
            continue
        if not in_subcommands:
            continue
        match = SUBCOMMAND.match(line)
        if match and match.group(1) != "help":
            names.append(match.group(1))
    return names


def command_help(binary):
    queue = [()]
    seen = set()
    sections = []
    while queue:
        path = queue.pop(0)
        if path in seen:
            raise SystemExit(f"duplicate command path: {path}")
        seen.add(path)
        help_text = run(binary, *path, "--help").decode()
        sections.append((path, help_text))
        queue.extend(path + (child,) for child in child_names(help_text))
    return sections


def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--binary", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if args.output.exists():
        raise SystemExit(f"destination already exists: {args.output}")

    completions = {
        "completions/worklouderctl.bash": "bash",
        "completions/_worklouderctl": "zsh",
        "completions/worklouderctl.fish": "fish",
    }
    for relative_path, shell in completions.items():
        write(args.output / relative_path, run(args.binary, "completion", shell))

    sections = command_help(args.binary)
    version = run(args.binary, "version").decode().strip()
    lines = [
        "<!-- Generated by scripts/render-cli-assets.py; do not edit by hand. -->",
        "# WorkLouderCTL command reference",
        "",
        f"Generated from `{version}`. This document contains {len(sections)} command paths.",
        "",
    ]
    for path, help_text in sections:
        command = " ".join(("worklouderctl",) + path)
        normalized_help = "\n".join(
            line.rstrip() for line in help_text.rstrip().splitlines()
        )
        lines.extend([f"## `{command}`", "", "```text", normalized_help, "```", ""])
    content = "\n".join(lines).rstrip() + "\n"
    write(args.output / "docs/command-reference.md", content.encode())


if __name__ == "__main__":
    main()
